[general]
import = [
  "~/.config/alacritty/themes/monokai_charcoal.toml"
]

[font]
  size = 10.70

[font.normal]
  family = "AdwaitaMono Nerd Font Mono"
  style = "Regular"

[font.bold]
  family = "AdwaitaMono Nerd Font Mono"
  style = "Bold"

[font.italic]
  family = "AdwaitaMono Nerd Font Mono"
  style = "Italic"

[font.bold_italic]
  family = "AdwaitaMono Nerd Font Mono"
  style = "Bold Italic"

# alacritty.toml
[[keyboard.bindings]]
key = "E"
mods = "Shift|Control"
chars = "\x1b[69;6u"   # CSI u-encoding for Shift+Ctrl+E

