[general]
import = [
  "~/.config/alacritty/themes/monokai_charcoal.toml"
]

[font]
  size = 10.90

[font.normal]
  family = "AdwaitaMono Nerd Font Mono"
  style = "Regular"

[font.bold]
  family = "AdwaitaMono Nerd Font Mono"
  style = "Bold"

[font.italic]
  family = "AdwaitaMono Nerd Font Mono"
  style = "Italic"

[font.bold_italic]
  family = "AdwaitaMono Nerd Font Mono"
  style = "Bold Italic"
